import { SubjectContent } from "../types";

const content: SubjectContent = {
  code: "24ERT402",
  name: "Signals & Systems",
  semester: "s4",
  category: "math",
  credits: 3,
  ltpj: "2-1-0-0",
  modules: [
    {
      id: "m1",
      number: 1,
      title: "Introduction to Signals and Systems",
      topics: [
        { title: "Introduction to signals and systems -Elementary signals – unit step, unit ramp, unit impulse - properties, real and complex exponentials, sinusoidal" },
        { title: "Classification of signals – Continuous Time and Discrete Time, Even and Odd, Causal an Noncausal, Periodic and Aperiodic, Power and Energy, Deterministic and Random signals" },
        { title: "Basic operations on signals – reversal, shifting, scaling (both time and amplitude)" },
        { title: "Concept of system - Properties of systems - linearity, time invariance, causality, memor stability, invertibility – Numerical problems" },
        { title: "Use simulation platforms (MATLAB / Scilab) to demonstrate elementary signals and it operations (HomeWorks / Assignments only)" },
      ],
      overview: {
        summary: "Syllabus module 1: Introduction to Signals and Systems. Detailed exam-focused notes are not written yet; the official syllabus topics are listed below.",
        whyItMatters: "Part of the official Signals & Systems (24ERT402) — Semester 4. Use the topics below with the AI study prompts while detailed notes are being written.",
      },
      coreConcepts: [
        "Introduction to signals and systems -Elementary signals – unit step, unit ramp, unit impulse - properties, real and complex exponentials, sinusoidal",
        "Classification of signals – Continuous Time and Discrete Time, Even and Odd, Causal an Noncausal, Periodic and Aperiodic, Power and Energy, Deterministic and Random signals",
        "Basic operations on signals – reversal, shifting, scaling (both time and amplitude)",
        "Concept of system - Properties of systems - linearity, time invariance, causality, memor stability, invertibility – Numerical problems",
        "Use simulation platforms (MATLAB / Scilab) to demonstrate elementary signals and it operations (HomeWorks / Assignments only)",
      ],
      definitions: [],
      diagrams: [],
      formulas: [],
      examFocus: [],
      revisionNotes: [],
    },
    {
      id: "m2",
      number: 2,
      title: "Convolution and Laplace Transform Analysis",
      topics: [
        { title: "Convolution integral – Analytical method" },
        { title: "Representation of LTI systems - Impulse response representation – Differential equation representations of LTI systems" },
        { title: "Overview of Laplace Transform - Laplace transform analysis of systems – Relation between th transfer function and differential equation" },
        { title: "Determining the time domain response from transfer function – Numerical problems o electrical networks" },
        { title: "Use simulation platforms (MATLAB / Scilab) to obtain time domain response from transfe function" },
        { title: "(HomeWorks / Assignments only)" },
      ],
      overview: {
        summary: "Syllabus module 2: Convolution and Laplace Transform Analysis. Detailed exam-focused notes are not written yet; the official syllabus topics are listed below.",
        whyItMatters: "Part of the official Signals & Systems (24ERT402) — Semester 4. Use the topics below with the AI study prompts while detailed notes are being written.",
      },
      coreConcepts: [
        "Convolution integral – Analytical method",
        "Representation of LTI systems - Impulse response representation – Differential equation representations of LTI systems",
        "Overview of Laplace Transform - Laplace transform analysis of systems – Relation between th transfer function and differential equation",
        "Determining the time domain response from transfer function – Numerical problems o electrical networks",
        "Use simulation platforms (MATLAB / Scilab) to obtain time domain response from transfe function",
        "(HomeWorks / Assignments only)",
      ],
      definitions: [],
      diagrams: [],
      formulas: [],
      examFocus: [],
      revisionNotes: [],
    },
    {
      id: "m3",
      number: 3,
      title: "Fourier Representation and Sampling of Signals.",
      topics: [
        { title: "Fourier representation of continuous time signals – Fourier Series – Harmonic analysis of common signals Fourier transform – Existence – properties of FT, Frequency response of LTI systems Sampling process- sampling theorem– Aliasing – Nyquist rate" },
        { title: "Signal reconstruction- Zero order and First order hold circuits" },
        { title: "Use simulation platforms (MATLAB / Scilab) to obtain Fourier Series / Transform of common signals" },
        { title: "(HomeWorks / Assignments only)" },
      ],
      overview: {
        summary: "Syllabus module 3: Fourier Representation and Sampling of Signals.. Detailed exam-focused notes are not written yet; the official syllabus topics are listed below.",
        whyItMatters: "Part of the official Signals & Systems (24ERT402) — Semester 4. Use the topics below with the AI study prompts while detailed notes are being written.",
      },
      coreConcepts: [
        "Fourier representation of continuous time signals – Fourier Series – Harmonic analysis of common signals Fourier transform – Existence – properties of FT, Frequency response of LTI systems Sampling process- sampling theorem– Aliasing – Nyquist rate",
        "Signal reconstruction- Zero order and First order hold circuits",
        "Use simulation platforms (MATLAB / Scilab) to obtain Fourier Series / Transform of common signals",
        "(HomeWorks / Assignments only)",
      ],
      definitions: [],
      diagrams: [],
      formulas: [],
      examFocus: [],
      revisionNotes: [],
    },
    {
      id: "m4",
      number: 4,
      title: "Discrete domain representation of signals and systems.",
      topics: [
        { title: "Difference equation representations of LTI systems - Discrete forms of representing systems – Direct form I and II, Cascade, Parallel forms" },
        { title: "Fourier representation of discrete time signals - Discrete Fourier series – properties" },
        { title: "Discrete time Fourier Transform – properties of DTFT" },
        { title: "Frequency response of Discrete Time systems" },
        { title: "Use simulation platforms (MATLAB / Scilab) to obtain Discrete Fourier Series / Transform of common signals" },
        { title: "(HomeWorks / Assignments only)" },
      ],
      overview: {
        summary: "Syllabus module 4: Discrete domain representation of signals and systems.. Detailed exam-focused notes are not written yet; the official syllabus topics are listed below.",
        whyItMatters: "Part of the official Signals & Systems (24ERT402) — Semester 4. Use the topics below with the AI study prompts while detailed notes are being written.",
      },
      coreConcepts: [
        "Difference equation representations of LTI systems - Discrete forms of representing systems – Direct form I and II, Cascade, Parallel forms",
        "Fourier representation of discrete time signals - Discrete Fourier series – properties",
        "Discrete time Fourier Transform – properties of DTFT",
        "Frequency response of Discrete Time systems",
        "Use simulation platforms (MATLAB / Scilab) to obtain Discrete Fourier Series / Transform of common signals",
        "(HomeWorks / Assignments only)",
      ],
      definitions: [],
      diagrams: [],
      formulas: [],
      examFocus: [],
      revisionNotes: [],
    },
    {
      id: "m5",
      number: 5,
      title: "Discrete Convolution and Z Transform Analysis",
      topics: [
        { title: "Discrete convolution- methods and its properties" },
        { title: "Z Transform - Region of convergence- Properties of the Z transform, Inverse ZT –Long division, Partial Fraction methods" },
        { title: "Z-transfer function- Analysis of difference equation of LTI systems – Mapping of Laplace- domain to Z-domain" },
        { title: "Use simulation platforms (MATLAB / Scilab) to analyze discrete systems using Z- transform" },
        { title: "(HomeWorks / Assignments only)" },
      ],
      overview: {
        summary: "Syllabus module 5: Discrete Convolution and Z Transform Analysis. Detailed exam-focused notes are not written yet; the official syllabus topics are listed below.",
        whyItMatters: "Part of the official Signals & Systems (24ERT402) — Semester 4. Use the topics below with the AI study prompts while detailed notes are being written.",
      },
      coreConcepts: [
        "Discrete convolution- methods and its properties",
        "Z Transform - Region of convergence- Properties of the Z transform, Inverse ZT –Long division, Partial Fraction methods",
        "Z-transfer function- Analysis of difference equation of LTI systems – Mapping of Laplace- domain to Z-domain",
        "Use simulation platforms (MATLAB / Scilab) to analyze discrete systems using Z- transform",
        "(HomeWorks / Assignments only)",
      ],
      definitions: [],
      diagrams: [],
      formulas: [],
      examFocus: [],
      revisionNotes: [],
    }
  ],
};

export default content;
