import { SubjectContent } from "../types";

const content: SubjectContent = {
  subjectCode: "24ESP307",
  modules: [
    // ---------------------------------------------------------------
    // MODULE I — Introduction to Electrical Circuit Simulation
    // ---------------------------------------------------------------
    {
      id: "m1",
      title: "Introduction to Electrical Circuit Simulation",
      overview: {
        summary:
          "This module covers what system simulation is, why it's used in electrical engineering, the different categories of simulation problems (DC, transient, AC, digital), and the supporting analyses — sensitivity and noise analysis.",
        whyItMatters:
          "This is a lab course, so the 'exam' is really the lab viva and end-semester practical exam. Examiners use this module's terminology — DC/transient/AC/digital simulation, sensitivity analysis, noise analysis — as quick viva questions before asking you to actually run a simulation, so being able to define and differentiate these fast sets the tone for the rest of the viva.",
      },
      coreConcepts: [
        "System simulation = building a computer model of a real circuit/system and running it to predict behaviour without building physical hardware — much faster and cheaper than breadboard prototyping for early-stage design.",
        "Advantages: low cost, fast iteration, safe to test extreme/dangerous conditions, easy to change parameters. Disadvantages: model accuracy depends entirely on how well it represents the real component (parasitics, tolerances, non-idealities are easy to miss).",
        "DC simulation: finds the circuit's operating point (bias point) assuming all sources are constant and have been applied for a long time (steady state, no time variation).",
        "Transient simulation: solves the circuit's behaviour as a function of time from some starting condition (e.g. switch closing) — this is where time constants, rise times, and settling behaviour show up.",
        "AC simulation: analyses the circuit's steady-state response across a range of frequencies (e.g. for frequency response / Bode plots), using small-signal linearization around a DC operating point.",
        "Digital circuit simulation: simulates logic-level (0/1) behaviour of digital circuits, often timing-aware (gate delays, setup/hold violations) rather than continuous voltage/current.",
        "Sensitivity analysis: measures how much a circuit's output changes in response to small variations in a component's value — used to identify which components most affect performance and need tighter tolerance.",
        "Noise analysis: estimates the noise generated by circuit components (thermal, shot, flicker noise) and how it propagates to the output, important for low-signal/precision circuits.",
      ],
      definitions: [
        { term: "System Simulation", definition: "The use of a computer model to predict the behaviour of a real electrical system or circuit under specified conditions, without needing to build physical hardware." },
        { term: "DC Simulation", definition: "A simulation that determines a circuit's steady-state operating point under constant (time-invariant) source values." },
        { term: "Transient Simulation", definition: "A simulation that computes a circuit's time-domain response starting from a given initial condition, capturing rise times, settling, and switching behaviour." },
        { term: "AC Simulation", definition: "A simulation that determines a linearized circuit's steady-state response across a sweep of frequencies, typically around a DC operating point." },
        { term: "Sensitivity Analysis", definition: "An analysis that quantifies how much a circuit's output changes for a small change in a given component's parameter value." },
        { term: "Noise Analysis", definition: "An analysis that estimates the noise contributed by circuit components and how it appears, referred to the circuit's output." },
      ],
      diagrams: [
        { title: "Categories of circuit simulation", svgKey: "simulation-types-flow", caption: "Each simulation type answers a different question about the same circuit — operating point, time response, frequency response, or logic behaviour." },
      ],
      formulas: [
        { name: "Sensitivity (definition)", expression: "S = (∂Output / ∂Parameter) × (Parameter / Output)", note: "A normalized 'percent change in output per percent change in parameter' — higher |S| means that component matters more." },
      ],
      examFocus: [
        { question: "Differentiate DC, Transient, and AC simulation — what question does each answer about the circuit?", weightage: "high", note: "Common opening viva question before being asked to actually run one." },
        { question: "Explain sensitivity analysis and why it matters in circuit design.", weightage: "medium" },
        { question: "Explain noise analysis and the types of noise it accounts for.", weightage: "medium" },
        { question: "List advantages and disadvantages of simulation over physical prototyping.", weightage: "medium" },
      ],
      revisionNotes: [
        "DC sim → steady operating point (no time variation).",
        "Transient sim → response over time from a starting condition.",
        "AC sim → frequency response, small-signal, around a DC point.",
        "Digital sim → logic-level (0/1), often timing-aware.",
        "Sensitivity analysis → which component matters most to the output.",
        "Noise analysis → how component noise reaches the output.",
      ],
      intuition:
        "DC, transient, and AC simulation aren't three different tools for three different circuits — they're three different QUESTIONS about the SAME circuit: 'where does it settle?' (DC), 'how does it get there?' (transient), and 'how does it respond if I wiggle it at different speeds?' (AC).",
      selfCheck: [
        { question: "If you only care about a circuit's behaviour after all switching transients have died out, which simulation type do you need?", answer: "DC simulation (for a constant-source steady state) or AC simulation (for a sinusoidal steady state) — transient simulation is specifically for capturing what happens DURING the settling process, not after it." },
        { question: "Why would a designer run a sensitivity analysis before committing to final component tolerances?", answer: "Sensitivity analysis reveals which components' value variations affect the output the most. Knowing this lets a designer spend money on tight tolerances only where it actually matters, and allow cheaper, looser tolerances on components the output barely depends on." },
      ],
    },

    // ---------------------------------------------------------------
    // MODULE II — Introduction to MATLAB
    // ---------------------------------------------------------------
    {
      id: "m2",
      title: "Introduction to MATLAB",
      overview: {
        summary:
          "This module covers MATLAB fundamentals: variables, arrays, conditional statements, loops, functions, m-files, plotting, toolbox familiarization, and solving ordinary differential equations using built-in ODE solvers.",
        whyItMatters:
          "The practical exam will almost certainly ask you to write a short MATLAB script live — usually plotting something or solving a simple ODE. Knowing the exact syntax cold (not just 'understanding the concept') is what actually scores marks here.",
      },
      coreConcepts: [
        "MATLAB variables are untyped and created on assignment (no declaration needed); everything is fundamentally a matrix — a scalar is just a 1×1 matrix.",
        "Arrays: row vectors with [ ], ranges with start:step:end, matrices by separating rows with ; — indexing starts at 1, not 0.",
        "Conditional statements (if/elseif/else) and loops (for, while) follow a block...end structure rather than braces.",
        "Functions can be defined in their own .m file (filename must match function name) or as local functions within a script — they take inputs, return outputs, and have their own variable scope.",
        "m-files: .m script files run a sequence of commands; .m function files define reusable functions — both are plain text and edited in the MATLAB editor.",
        "Plotting: plot(x,y) for 2D line plots, with xlabel/ylabel/title/legend/grid for labeling — essential for visualizing simulation results.",
        "Toolboxes extend MATLAB's base functionality for specific domains (Control System Toolbox, Signal Processing Toolbox, Simulink, etc.) — familiarity with which toolbox has which function matters for picking the right command.",
        "Ordinary Differential Equations (ODEs) describing a dynamic system can be solved numerically using built-in solvers like ode45 (general-purpose, most commonly used) — you write the derivative as a function and pass it to the solver with a time span and initial condition.",
      ],
      definitions: [
        { term: "m-file", definition: "A plain-text MATLAB file with a .m extension, either a script (sequence of commands) or a function file (defines a reusable function)." },
        { term: "ODE Solver", definition: "A built-in MATLAB function (e.g. ode45) that numerically integrates a system of ordinary differential equations over a specified time span given an initial condition." },
        { term: "Toolbox", definition: "A collection of specialized MATLAB functions and tools for a specific application domain (e.g. control systems, signal processing), extending MATLAB's base capability." },
      ],
      diagrams: [],
      formulas: [
        { name: "Create a vector / range", expression: "x = 0:0.1:10;        % start:step:end" },
        { name: "Basic 2D plot", expression: "plot(x, y); xlabel('t'); ylabel('y'); title('Response'); grid on;" },
        { name: "for loop", expression: "for i = 1:n\n   ...\nend" },
        { name: "if-elseif-else", expression: "if cond1\n   ...\nelseif cond2\n   ...\nelse\n   ...\nend" },
        { name: "Function file template", expression: "function out = myFunc(in1, in2)\n   out = in1 + in2;\nend" },
        { name: "Solve an ODE with ode45", expression: "[t, y] = ode45(@(t,y) -2*y, [0 5], 1);   % dy/dt = -2y, y(0)=1" },
      ],
      examFocus: [
        { question: "Write a MATLAB script to plot a given function or simulation result with proper axis labels.", weightage: "high", note: "Marks are lost for missing xlabel/ylabel/title even if the plot itself is correct." },
        { question: "Write a MATLAB function to solve a given first-order ODE using ode45.", weightage: "high" },
        { question: "Write a MATLAB program using a for/while loop and a conditional statement to solve a given small problem.", weightage: "medium" },
        { question: "Differentiate a script m-file from a function m-file.", weightage: "low" },
      ],
      revisionNotes: [
        "Indexing starts at 1. [ ] for arrays/vectors, ; separates matrix rows.",
        "for ... end / if ... elseif ... else ... end — no braces.",
        "Function file name MUST match the function name inside it.",
        "plot(x,y) + xlabel/ylabel/title/grid — always label your plots.",
        "ode45(@(t,y) f(t,y), tspan, y0) is the go-to general ODE solver.",
      ],
      intuition:
        "MATLAB treats EVERYTHING as a matrix, even a single number — that's not a quirk, it's the whole design philosophy. Once you stop thinking 'this is a number, that's an array' and just think 'these are all matrices of different shapes', operations like elementwise multiplication and vectorized loops stop being special cases and start feeling automatic.",
      workedExamples: [
        {
          title: "Write a MATLAB script to plot a function",
          problem: "Write MATLAB code to plot y = sin(x) for x from 0 to 2π, with proper labels.",
          steps: [
            { label: "Step 1: Create the x values", content: "x = 0:0.01:2*pi;   % fine step for a smooth curve" },
            { label: "Step 2: Compute y", content: "y = sin(x);   % MATLAB applies sin() to every element automatically" },
            { label: "Step 3: Plot and label", content: "plot(x, y); xlabel('x'); ylabel('sin(x)'); title('Sine Wave'); grid on;" },
          ],
          answer: "A labeled sine curve from 0 to 2π — note step 2 needed no loop at all, since MATLAB operations apply elementwise to the whole vector by default.",
        },
      ],
      selfCheck: [
        { question: "Why does y = sin(x) work directly on a whole vector x in MATLAB, without writing a for loop?", answer: "MATLAB functions are designed to operate elementwise on matrices/vectors by default — sin() is applied to every element of x simultaneously, producing a same-sized vector y. This 'vectorization' is one of MATLAB's core design principles." },
        { question: "If your function file is named addTwo.m but the function inside is defined as function out = sumThem(a,b), what happens when you try to call addTwo(3,4)?", answer: "MATLAB requires the function name to match the file name exactly, so this would produce an error or unexpected behavior — rename either the file to sumThem.m or the function definition to function out = addTwo(a,b)." },
      ],
    },

    // ---------------------------------------------------------------
    // MODULE III — Creating Subsystems using MATLAB/SIMULINK
    // ---------------------------------------------------------------
    {
      id: "m3",
      title: "Creating Subsystems using MATLAB/SIMULINK",
      overview: {
        summary:
          "This module covers SIMULINK — MATLAB's block-diagram simulation environment — its interface, libraries, sources and sinks, and the process of converting a mathematical model into a working SIMULINK model.",
        whyItMatters:
          "The practical exam typically gives you a simple mathematical model (a differential equation or transfer function) and asks you to build and simulate it in SIMULINK — knowing the standard blocks (Step, Integrator, Gain, Scope) by name and where to find them in the library browser is what saves you time under exam pressure.",
      },
      coreConcepts: [
        "SIMULINK is a graphical, block-diagram extension of MATLAB for modeling, simulating, and analysing dynamic systems — instead of writing code, you connect functional blocks with signal lines.",
        "The Simulink Library Browser organizes blocks into categories: Sources (signal generators — Step, Sine Wave, Ramp, Constant), Sinks (display/output — Scope, Display, To Workspace), Continuous (Integrator, Transfer Fcn, State-Space), Math Operations (Gain, Sum, Product), and more.",
        "Building a system: drag blocks from the library onto the canvas, connect their input/output ports with signal lines, set each block's parameters (double-click to open its dialog), then run the simulation and view results on a Scope.",
        "Converting a mathematical model into SIMULINK: write the system as a differential equation, isolate the highest derivative, and build the diagram backward from it using Integrator blocks (each integrator block reduces a derivative order by one) connected through Gain and Sum blocks representing the equation's coefficients.",
        "A 'subsystem' groups a set of connected blocks into a single block with its own input/output ports — used to organize large models and to make a reusable sub-model.",
      ],
      definitions: [
        { term: "SIMULINK", definition: "A graphical block-diagram environment within MATLAB used to model, simulate, and analyse dynamic systems by connecting functional blocks instead of writing sequential code." },
        { term: "Source block", definition: "A SIMULINK block that generates a signal with no input of its own (e.g. Step, Sine Wave, Constant) — used to drive a model." },
        { term: "Sink block", definition: "A SIMULINK block that consumes a signal to display or record it (e.g. Scope, Display, To Workspace) — has no output of its own." },
        { term: "Subsystem", definition: "A group of connected SIMULINK blocks collapsed into a single block with defined input/output ports, used to simplify and modularize a larger model." },
      ],
      diagrams: [
        { title: "Building a SIMULINK model from sources to sinks", svgKey: "simulink-block-diagram", caption: "A Source block drives the system under test, and a Sink (Scope) displays the resulting signal — everything in between is the actual model." },
      ],
      formulas: [
        { name: "Differential equation → Integrator chain (rule of thumb)", expression: "highest derivative → Integrator → next-lower derivative → Integrator → ... → output", note: "Each Integrator block reduces the derivative order by exactly one; Gain blocks apply the equation's coefficients, Sum blocks combine terms." },
      ],
      examFocus: [
        { question: "Build a SIMULINK model for a given first/second-order differential equation and simulate its step response.", weightage: "high", note: "Practice the Integrator-chain construction until it's automatic — this is the centerpiece practical task." },
        { question: "Identify and explain the function of standard SIMULINK blocks (Step, Scope, Gain, Integrator, Sum) used in a given model.", weightage: "high" },
        { question: "Differentiate Source and Sink blocks with examples.", weightage: "medium" },
        { question: "Explain the purpose and creation of a subsystem in SIMULINK.", weightage: "low" },
      ],
      revisionNotes: [
        "SIMULINK = block diagrams instead of code, for dynamic system modeling.",
        "Sources (Step, Sine, Constant) generate signals; Sinks (Scope, Display) consume them.",
        "Build from the highest derivative backward using Integrator + Gain + Sum blocks.",
        "Subsystem = group of blocks collapsed into one reusable block.",
      ],
      intuition:
        "An Integrator block is just a promise: 'whatever you feed me, I'll accumulate it over time.' Building a differential equation backward from its highest derivative works because integrating dⁿx/dtⁿ once gives you dⁿ⁻¹x/dtⁿ⁻¹ — chain enough Integrators together and you walk all the way down to x(t) itself.",
      workedExamples: [
        {
          title: "Build a SIMULINK model from a differential equation",
          problem: "You need to model dx/dt = −2x + u(t), where u(t) is a step input. Describe the SIMULINK block arrangement.",
          steps: [
            { label: "Step 1: Identify the highest derivative", content: "dx/dt is the highest (and only) derivative here — it will come out of an Integrator's input." },
            { label: "Step 2: Express dx/dt in terms of available signals", content: "dx/dt = u(t) − 2x. You need a Sum block combining u(t) (from a Step source) and −2x (x fed back through a Gain block of −2)." },
            { label: "Step 3: Wire it up", content: "Step source → Sum block (+input). Integrator's OUTPUT (x) feeds back through a Gain of −2 → Sum block (second input). Sum block's output feeds the Integrator's input. Integrator's output (x) also feeds a Scope." },
          ],
          answer: "Step → Sum(+) ← Gain(−2) ← [Integrator output x] ; Sum output → Integrator → x → Scope (and feeds back to the Gain block)",
        },
      ],
      selfCheck: [
        { question: "Why can't you build a SIMULINK model for a 2nd-order differential equation with just ONE Integrator block?", answer: "Each Integrator reduces the derivative order by exactly one. A 2nd-order equation has a 2nd derivative as its highest term, so you need TWO Integrators in series to walk down from the 2nd derivative to the 1st derivative, and then to the variable itself." },
        { question: "What's the practical benefit of collapsing a group of blocks into a Subsystem rather than leaving them all visible?", answer: "It simplifies a large model visually (showing one block instead of dozens) and makes that group reusable — you can drop the same subsystem into multiple models instead of rebuilding the same block arrangement each time." },
      ],
    },

    // ---------------------------------------------------------------
    // MODULE IV — Electronic Instrumentation
    // ---------------------------------------------------------------
    {
      id: "m4",
      title: "Electronic Instrumentation",
      overview: {
        summary:
          "This module covers the building blocks of digital measurement instruments: A/D and D/A converters, instrumentation amplifiers, comparators and function generators, the internals of a digital multimeter, Hall-effect and clamp-on current sensing, and how frequency/phase/time-period and waveform capture (DSO) actually work.",
        whyItMatters:
          "This is the most viva-heavy module since you've physically used most of this equipment (DMM, DSO, function generator) in the lab — examiners often point at the actual instrument and ask you to explain a block inside it, so being able to name and explain each functional block from memory matters more than pure theory recall.",
      },
      coreConcepts: [
        "A/D Converter (ADC): converts a continuous analog voltage into a discrete digital code; D/A Converter (DAC): the reverse, converting a digital code back into an analog voltage — both are core to any digital measuring instrument.",
        "Instrumentation Amplifier: a precision differential amplifier with very high input impedance and high common-mode rejection, used to amplify small differential signals (e.g. from a sensor bridge) while rejecting common noise.",
        "Comparator: a circuit (often an op-amp used open-loop) that outputs one of two states depending on whether the input voltage is above or below a reference — the basis of zero-crossing/threshold detection.",
        "Function generator: an instrument that produces standard waveforms (sine, square, triangle) at adjustable frequency and amplitude, used to test/stimulate circuits under measurement.",
        "Digital Multimeter (DMM) internals: an input signal is conditioned (attenuated/amplified, AC signals rectified to DC), converted by an ADC, then displayed digitally — the same ADC core handles voltage, current (via a shunt), and resistance (via a known current source) measurement modes.",
        "Hall-effect sensor: produces a voltage proportional to a magnetic field, used in clamp-on (non-contact) current meters to sense the magnetic field around a current-carrying conductor without breaking the circuit.",
        "Solid-state energy meter: replaces the old mechanical induction-disc meter with ADC sampling of voltage and current plus digital multiplication to compute real power/energy electronically.",
        "Frequency, phase angle, and time period measurement: a Digital Storage Oscilloscope (DSO) samples and digitizes the waveform, letting frequency/period be read directly off the captured cycle, and phase angle measured as the time-shift between two channels converted to degrees.",
        "Sample and Hold circuit: captures ('samples') an analog signal's instantaneous value and holds it steady — required immediately before an ADC, since the ADC needs a stable input voltage for the duration of its conversion.",
      ],
      definitions: [
        { term: "A/D Converter (ADC)", definition: "A circuit that converts a continuous analog voltage into a corresponding discrete digital code." },
        { term: "D/A Converter (DAC)", definition: "A circuit that converts a discrete digital code into a corresponding continuous analog voltage." },
        { term: "Instrumentation Amplifier", definition: "A precision differential amplifier with high input impedance and high common-mode rejection ratio, designed to accurately amplify small differential signals while rejecting common-mode noise." },
        { term: "Sample and Hold Circuit", definition: "A circuit that captures the instantaneous value of an analog signal and holds it constant for a period, typically used to provide a stable input to an ADC during its conversion time." },
        { term: "Hall Effect Sensor", definition: "A sensor that produces an output voltage proportional to the strength of a magnetic field it is exposed to, used for non-contact magnetic field or current sensing." },
        { term: "Digital Storage Oscilloscope (DSO)", definition: "An oscilloscope that samples and digitizes an input waveform, storing it in memory so it can be displayed, measured, and analysed digitally." },
      ],
      diagrams: [
        { title: "ADC / DAC conversion block", svgKey: "adc-dac-block", caption: "A Sample-and-Hold circuit feeds a stable voltage into the ADC; the DAC performs the reverse conversion back to analog." },
      ],
      formulas: [
        { name: "Phase angle from time shift (DSO measurement)", expression: "φ (degrees) = (Δt / T) × 360°", note: "Δt = measured time shift between two waveforms, T = period of the waveform." },
      ],
      examFocus: [
        { question: "Explain the internal block diagram and working of a digital multimeter.", weightage: "high" },
        { question: "Explain the need for a Sample-and-Hold circuit immediately before an ADC.", weightage: "high" },
        { question: "Explain the working principle of a Hall-effect-based clamp-on current meter.", weightage: "medium" },
        { question: "Explain how a DSO is used to measure frequency, time period, and phase angle of a given waveform.", weightage: "high", note: "Be ready to demonstrate this live on the actual DSO during the practical exam." },
        { question: "Explain the working of an instrumentation amplifier and why it's preferred over a simple op-amp differential amplifier.", weightage: "medium" },
      ],
      revisionNotes: [
        "ADC: analog → digital code. DAC: digital code → analog.",
        "Sample & Hold must precede ADC — gives it a stable input during conversion.",
        "Instrumentation amp: high Zin, high CMRR, amplifies small differential signals.",
        "DMM internals: signal conditioning → ADC → digital display.",
        "Hall sensor → clamp meter: senses magnetic field, no circuit break needed.",
        "DSO: digitizes waveform → read frequency/period directly, phase via Δt/T×360°.",
      ],
      intuition:
        "An ADC is like a camera shutter — it needs the scene to stay still for the instant the shutter is open, or the photo blurs. A Sample-and-Hold circuit is that freeze-frame: it grabs the signal's value and holds it rock-steady just long enough for the ADC to 'photograph' it accurately.",
      comparisons: [
        {
          title: "Contact (Shunt) vs Non-Contact (Hall/Clamp) Current Sensing",
          scenario: "Both measure current flowing through a wire — but one requires breaking the circuit and one doesn't.",
          a: { label: "Shunt resistor", body: "Inserted IN SERIES with the circuit — current must physically flow through it. Requires breaking the circuit to install. Simple, accurate, but invasive." },
          b: { label: "Hall-effect clamp meter", body: "Clamps AROUND the conductor, sensing the magnetic field the current produces. No circuit break needed at all — purely non-contact." },
          takeaway: "Whenever you see 'measure current without disturbing the circuit', that's the Hall-effect/clamp-meter approach, not a shunt.",
        },
      ],
      selfCheck: [
        { question: "Why would feeding an ADC a signal that's still changing (without a Sample-and-Hold) cause measurement errors?", answer: "An ADC takes a finite amount of time to complete its conversion. If the input voltage keeps changing during that window, the digital code produced doesn't correspond cleanly to any single instant's value — it's a blurred mix of whatever the signal did during the conversion." },
        { question: "What specifically makes an instrumentation amplifier better suited than a plain op-amp differential amplifier for amplifying a sensor's small signal?", answer: "An instrumentation amplifier has much higher input impedance (so it doesn't load down/distort the sensor's weak signal) and much higher CMRR (so it rejects common-mode noise far more effectively) than a basic op-amp differential stage." },
      ],
      crossLinks: [
        { label: "LVDT and op-amp slew rate/CMRR also covered in Sensor & Sensor Circuits (Module IV)", href: "/s3/sensor-and-sensor-circuits#m4" },
      ],
    },

    // ---------------------------------------------------------------
    // MODULE V — Introduction to Virtual Instrumentation
    // ---------------------------------------------------------------
    {
      id: "m5",
      title: "Introduction to Virtual Instrumentation",
      overview: {
        summary:
          "This module covers Virtual Instrumentation (VI) — using software (e.g. LabVIEW) plus general-purpose hardware to replace dedicated instruments — including data structures (arrays, clusters), graphs/charts, string operations, data logging, DAQ hardware, PC bus architectures, and instrumentation buses.",
        whyItMatters:
          "VI concepts are usually tested as definitions/comparisons in the viva (e.g. 'array vs cluster', 'graph vs chart', 'DAQ vs traditional instrument') rather than numerically, so a tight grasp of each term's exact meaning earns quick, easy marks.",
      },
      coreConcepts: [
        "Virtual Instrumentation: combining a general-purpose computer with modular hardware (a DAQ device) and instrument-driver software so the software defines what the 'instrument' does — the same hardware can become a voltmeter, oscilloscope, or spectrum analyser just by changing the program.",
        "Arrays in a VI hold multiple elements of the SAME data type, indexed; Clusters bundle multiple elements of DIFFERENT data types together (similar to a struct/record) — this distinction is a very common viva question.",
        "Graphs display data after acquisition is complete (plot the whole data set at once); Charts display data continuously as it arrives, appending new points in real time — graphs are post-acquisition, charts are real-time/streaming.",
        "Programming techniques in VI environments are typically graphical/dataflow-based (e.g. LabVIEW's G language) — code execution is driven by data availability along wires rather than sequential line-by-line text.",
        "String operations let a VI build, parse, and format text — needed for things like formatting a data log file header or parsing an instrument's text-based response.",
        "Data logging: continuously writing acquired data to a file (e.g. CSV) over time for later analysis, rather than only displaying it live.",
        "DAQ (Data Acquisition) hardware: the physical device that samples real-world analog signals (via ADCs) and feeds the digital values into the PC, plus may output analog/digital signals for control.",
        "PC hardware and bus architecture for instrumentation: ISA and PCI are internal expansion buses for plugging DAQ cards directly into the computer; USB and PCMCIA are external/portable connection standards; instrumentation-specific buses include GPIB defined by IEEE 488.1, used for connecting and controlling standalone instruments from a computer.",
      ],
      definitions: [
        { term: "Virtual Instrumentation", definition: "An approach where general-purpose computer hardware combined with modular measurement hardware and software defines the function of an instrument, allowing the same hardware to be reconfigured into different instruments via software." },
        { term: "Array (in VI context)", definition: "A data structure holding multiple elements of the same data type, accessed by index." },
        { term: "Cluster (in VI context)", definition: "A data structure that bundles multiple elements of potentially different data types together into a single unit, similar to a struct/record." },
        { term: "DAQ (Data Acquisition) Hardware", definition: "Physical hardware that samples real-world analog signals (typically via an ADC) and transfers the digitized data to a computer, and may also generate analog/digital output signals." },
        { term: "IEEE 488.1 (GPIB)", definition: "A standard parallel instrumentation bus (General Purpose Interface Bus) used to connect and control multiple standalone test instruments from a single computer." },
      ],
      diagrams: [
        { title: "Virtual instrumentation system architecture", svgKey: "daq-system-architecture", caption: "Real-world signals enter through DAQ hardware (with its ADC), pass into the PC over a bus, and software defines what 'instrument' the system behaves as." },
      ],
      formulas: [],
      examFocus: [
        { question: "Differentiate an array and a cluster as used in a virtual instrument.", weightage: "high" },
        { question: "Differentiate a graph and a chart for displaying acquired data.", weightage: "high" },
        { question: "Explain the architecture of a typical data acquisition (DAQ) based virtual instrumentation system.", weightage: "high" },
        { question: "Differentiate ISA, PCI, USB, and PCMCIA as used for connecting DAQ hardware.", weightage: "medium" },
        { question: "Explain the purpose of IEEE 488.1 (GPIB) in instrumentation.", weightage: "medium" },
        { question: "Explain how data logging is implemented in a virtual instrument.", weightage: "low" },
      ],
      revisionNotes: [
        "VI = software defines the instrument; hardware (DAQ) stays general-purpose.",
        "Array = same data type, indexed. Cluster = different data types, bundled.",
        "Graph = plots after acquisition. Chart = plots in real time as data streams in.",
        "DAQ hardware = ADC + bus interface to the PC.",
        "ISA/PCI = internal buses. USB/PCMCIA = external/portable. GPIB (IEEE 488.1) = instrument control bus.",
      ],
      intuition:
        "A traditional oscilloscope is a single-purpose hammer — built to do exactly one job. Virtual instrumentation turns that hammer into a 3D printer: the same general-purpose hardware (DAQ) becomes whatever instrument the software currently tells it to be.",
      comparisons: [
        {
          title: "Array vs Cluster",
          scenario: "Both bundle multiple pieces of data together — but for very different reasons.",
          a: { label: "Array", body: "Multiple elements of the SAME type, accessed by index (e.g. 100 temperature readings). Good when you have many of the same kind of thing." },
          b: { label: "Cluster", body: "Multiple elements of DIFFERENT types bundled as one unit (e.g. a name, an ID number, and a status flag together) — like a struct/record." },
          takeaway: "If you'd loop over it with an index, it's an array. If you'd describe it as 'this thing has these properties', it's a cluster.",
        },
      ],
      selfCheck: [
        { question: "If you need to watch a sensor's reading update continuously while a test is running, would you use a graph or a chart?", answer: "A chart — it's designed to plot data continuously in real time as it streams in, appending new points live. A graph only displays a complete data set after acquisition is finished." },
        { question: "Why is GPIB (IEEE 488.1) categorized differently from USB or PCI in this module?", answer: "USB and PCI/ISA are general-purpose computer connection buses used for all kinds of peripherals. GPIB is specifically an instrumentation control bus, purpose-built for connecting and commanding standalone test instruments (like a function generator or DMM) from a controlling computer." },
      ],
    },
  ],
};

export default content;
