// Typing Practice — seeded technical sentences.
// "Improve your typing while learning Computer Science."
// Each sentence is tagged with category + difficulty so tests stay focused.
// Admin can edit/add/delete these (edits persist to localStorage, never this file).

import { TypingSentence } from "./types";

const curated: TypingSentence[] = [
  // ── General ───────────────────────────────────────────────────────────────
  { id: "gen-01", category: "general", difficulty: "beginner", sentence: "The operating system manages processes, memory, files, and hardware resources." },
  { id: "gen-02", category: "general", difficulty: "beginner", sentence: "Computers store and process data using billions of tiny electronic switches." },
  { id: "gen-03", category: "general", difficulty: "beginner", sentence: "A program is a list of instructions that tells a computer what to do." },
  { id: "gen-04", category: "general", difficulty: "intermediate", sentence: "Input devices send data to a computer, and output devices present the results." },
  { id: "gen-05", category: "general", difficulty: "intermediate", sentence: "Binary is the base two number system that all digital computers rely on internally." },
  { id: "gen-06", category: "general", difficulty: "intermediate", sentence: "An algorithm is a step by step procedure for solving a well defined problem." },
  { id: "gen-07", category: "general", difficulty: "advanced", sentence: "Von Neumann architecture stores both instructions and data in the same memory space." },
  { id: "gen-08", category: "general", difficulty: "advanced", sentence: "Throughput and latency measure how fast and how responsive a computing system really is." },

  // ── Programming ───────────────────────────────────────────────────────────
  { id: "prg-01", category: "programming", difficulty: "beginner", sentence: "A variable stores a value that can change while the program runs." },
  { id: "prg-02", category: "programming", difficulty: "beginner", sentence: "A function groups reusable statements under a single name." },
  { id: "prg-03", category: "programming", difficulty: "beginner", sentence: "Loops repeat a block of code until a condition becomes false." },
  { id: "prg-04", category: "programming", difficulty: "intermediate", sentence: "Conditional statements let a program choose between different paths of execution." },
  { id: "prg-05", category: "programming", difficulty: "intermediate", sentence: "An array stores a fixed number of elements of the same data type." },
  { id: "prg-06", category: "programming", difficulty: "intermediate", sentence: "Debugging is the process of finding and fixing errors in source code." },
  { id: "prg-07", category: "programming", difficulty: "advanced", sentence: "Recursion solves a problem by calling the same function on smaller inputs." },
  { id: "prg-08", category: "programming", difficulty: "advanced", sentence: "Compilers translate high level source code into machine code before execution." },
  { id: "prg-09", category: "programming", difficulty: "advanced", sentence: "Big O notation describes how an algorithm scales as the input size grows." },
  { id: "prg-10", category: "programming", difficulty: "intermediate", sentence: "Comments explain code to humans and are ignored by the compiler." },
  { id: "prg-11", category: "programming", difficulty: "beginner", sentence: "Strings are sequences of characters surrounded by quotes in most languages." },
  { id: "prg-12", category: "programming", difficulty: "intermediate", sentence: "Exception handling lets a program recover gracefully from runtime errors." },

  // ── Python ────────────────────────────────────────────────────────────────
  { id: "py-01", category: "python", difficulty: "beginner", sentence: "Python is widely used for automation, data science, machine learning, and backend development." },
  { id: "py-02", category: "python", difficulty: "beginner", sentence: "Python uses indentation to define blocks of code instead of curly braces." },
  { id: "py-03", category: "python", difficulty: "beginner", sentence: "Lists in Python are ordered, mutable collections that can hold mixed types." },
  { id: "py-04", category: "python", difficulty: "intermediate", sentence: "Dictionaries map keys to values and give fast lookups by key." },
  { id: "py-05", category: "python", difficulty: "intermediate", sentence: "Tuples are immutable sequences, so their contents cannot change after creation." },
  { id: "py-06", category: "python", difficulty: "intermediate", sentence: "List comprehensions build new lists concisely using a single expression." },
  { id: "py-07", category: "python", difficulty: "intermediate", sentence: "A lambda function is a small anonymous function defined inline." },
  { id: "py-08", category: "python", difficulty: "advanced", sentence: "Generators produce values lazily, one at a time, saving memory for large data." },
  { id: "py-09", category: "python", difficulty: "advanced", sentence: "Decorators wrap a function to extend its behavior without changing its code." },
  { id: "py-10", category: "python", difficulty: "advanced", sentence: "The global interpreter lock serializes thread execution in CPython, limiting true parallelism." },
  { id: "py-11", category: "python", difficulty: "beginner", sentence: "The print function sends its arguments to the standard output stream." },
  { id: "py-12", category: "python", difficulty: "intermediate", sentence: "The with statement guarantees that resources like files are properly released." },

  // ── C++ ───────────────────────────────────────────────────────────────────
  { id: "cpp-01", category: "cpp", difficulty: "beginner", sentence: "C++ combines low level control with high level object oriented features." },
  { id: "cpp-02", category: "cpp", difficulty: "beginner", sentence: "A header file declares functions and classes that other source files can use." },
  { id: "cpp-03", category: "cpp", difficulty: "intermediate", sentence: "Pointers store memory addresses and enable direct manipulation of memory." },
  { id: "cpp-04", category: "cpp", difficulty: "intermediate", sentence: "References provide an alias to an existing variable without copying it." },
  { id: "cpp-05", category: "cpp", difficulty: "intermediate", sentence: "Classes encapsulate data and the functions that operate on that data." },
  { id: "cpp-06", category: "cpp", difficulty: "advanced", sentence: "The standard template library provides generic containers and algorithms." },
  { id: "cpp-07", category: "cpp", difficulty: "advanced", sentence: "Templates let a single function or class work with many different data types." },
  { id: "cpp-08", category: "cpp", difficulty: "advanced", sentence: "Smart pointers automatically release memory when it is no longer referenced." },
  { id: "cpp-09", category: "cpp", difficulty: "intermediate", sentence: "Polymorphism lets derived classes override base class behavior at runtime." },
  { id: "cpp-10", category: "cpp", difficulty: "intermediate", sentence: "The new and delete operators allocate and free dynamic memory explicitly." },
  { id: "cpp-11", category: "cpp", difficulty: "beginner", sentence: "The cout object sends formatted output to the standard output stream." },
  { id: "cpp-12", category: "cpp", difficulty: "advanced", sentence: "Move semantics transfer ownership of resources instead of copying expensive data." },

  // ── Data Structures ───────────────────────────────────────────────────────
  { id: "ds-01", category: "ds", difficulty: "beginner", sentence: "A stack is a last in first out data structure with push and pop operations.", subject: "Data Structures and Algorithms", topic: "Stacks" },
  { id: "ds-02", category: "ds", difficulty: "beginner", sentence: "A queue processes elements in first in first out order.", subject: "Data Structures and Algorithms", topic: "Queues" },
  { id: "ds-03", category: "ds", difficulty: "beginner", sentence: "A linked list stores elements in nodes that point to the next node.", subject: "Data Structures and Algorithms", topic: "Linked Lists" },
  { id: "ds-04", category: "ds", difficulty: "intermediate", sentence: "An array gives constant time access to any element using its index.", subject: "Data Structures and Algorithms", topic: "Arrays" },
  { id: "ds-05", category: "ds", difficulty: "intermediate", sentence: "A hash table maps keys to values using a hash function for fast lookup.", subject: "Data Structures and Algorithms", topic: "Hashing" },
  { id: "ds-06", category: "ds", difficulty: "intermediate", sentence: "A binary tree is a hierarchical structure where each node has at most two children.", subject: "Data Structures and Algorithms", topic: "Trees" },
  { id: "ds-07", category: "ds", difficulty: "intermediate", sentence: "A binary search tree keeps left children smaller and right children larger than the root.", subject: "Data Structures and Algorithms", topic: "Trees" },
  { id: "ds-08", category: "ds", difficulty: "advanced", sentence: "A heap is a complete binary tree that satisfies the min heap or max heap property.", subject: "Data Structures and Algorithms", topic: "Heaps" },
  { id: "ds-09", category: "ds", difficulty: "advanced", sentence: "A graph consists of vertices connected by edges and models many real world networks.", subject: "Data Structures and Algorithms", topic: "Graphs" },
  { id: "ds-10", category: "ds", difficulty: "advanced", sentence: "A balanced tree keeps its height logarithmic to guarantee fast search and insertion.", subject: "Data Structures and Algorithms", topic: "Trees" },
  { id: "ds-11", category: "ds", difficulty: "intermediate", sentence: "A deque allows insertion and deletion at both ends of the sequence.", subject: "Data Structures and Algorithms", topic: "Queues" },
  { id: "ds-12", category: "ds", difficulty: "beginner", sentence: "A set stores unique elements and ignores duplicate insertions.", subject: "Data Structures and Algorithms", topic: "Sets" },
  { id: "ds-13", category: "ds", difficulty: "advanced", sentence: "A trie is a tree that stores strings character by character along its edges.", subject: "Data Structures and Algorithms", topic: "Tries" },
  { id: "ds-14", category: "ds", difficulty: "advanced", sentence: "Self balancing trees like AVL trees rotate nodes to preserve logarithmic height.", subject: "Data Structures and Algorithms", topic: "Trees" },

  // ── Algorithms ────────────────────────────────────────────────────────────
  { id: "alg-01", category: "algorithms", difficulty: "beginner", sentence: "Linear search scans each element until it finds the target value." },
  { id: "alg-02", category: "algorithms", difficulty: "intermediate", sentence: "The binary search algorithm repeatedly divides the search space in half." },
  { id: "alg-03", category: "algorithms", difficulty: "intermediate", sentence: "Bubble sort repeatedly swaps adjacent elements that are in the wrong order." },
  { id: "alg-04", category: "algorithms", difficulty: "intermediate", sentence: "Merge sort divides the array and merges sorted halves in linear time." },
  { id: "alg-05", category: "algorithms", difficulty: "advanced", sentence: "Quick sort partitions the array around a pivot and sorts each side recursively." },
  { id: "alg-06", category: "algorithms", difficulty: "intermediate", sentence: "Dijkstra's algorithm finds the shortest path in a weighted graph.", subject: "Data Structures and Algorithms", topic: "Graph Algorithms" },
  { id: "alg-07", category: "algorithms", difficulty: "advanced", sentence: "Depth first search explores a graph by going as deep as possible before backtracking." },
  { id: "alg-08", category: "algorithms", difficulty: "advanced", sentence: "Dynamic programming reuses subproblem solutions to avoid recomputing them." },
  { id: "alg-09", category: "algorithms", difficulty: "advanced", sentence: "Greedy algorithms make the locally optimal choice at every single step." },
  { id: "alg-10", category: "algorithms", difficulty: "beginner", sentence: "Recursion expresses an algorithm in terms of itself with a base case." },
  { id: "alg-11", category: "algorithms", difficulty: "advanced", sentence: "The knapsack problem chooses items to maximize value within a weight limit." },
  { id: "alg-12", category: "algorithms", difficulty: "advanced", sentence: "Divide and conquer breaks a problem into smaller independent subproblems." },
  { id: "alg-13", category: "algorithms", difficulty: "advanced", sentence: "Backtracking tries candidates and abandons partial solutions that cannot work." },
  { id: "alg-14", category: "algorithms", difficulty: "intermediate", sentence: "Breadth first search visits all neighbors before moving to the next level." },

  // ── DBMS ──────────────────────────────────────────────────────────────────
  { id: "db-01", category: "dbms", difficulty: "beginner", sentence: "A database is an organized collection of data that can be accessed efficiently." },
  { id: "db-02", category: "dbms", difficulty: "beginner", sentence: "A primary key uniquely identifies each row in a database table." },
  { id: "db-03", category: "dbms", difficulty: "intermediate", sentence: "SQL is the standard language for querying and manipulating relational databases." },
  { id: "db-04", category: "dbms", difficulty: "intermediate", sentence: "A foreign key links rows in one table to rows in another table." },
  { id: "db-05", category: "dbms", difficulty: "intermediate", sentence: "Normalization removes redundant data to reduce update anomalies." },
  { id: "db-06", category: "dbms", difficulty: "intermediate", sentence: "Transactions group operations that must succeed or fail as a single unit." },
  { id: "db-07", category: "dbms", difficulty: "advanced", sentence: "ACID properties guarantee atomicity, consistency, isolation, and durability." },
  { id: "db-08", category: "dbms", difficulty: "advanced", sentence: "A B tree index speeds up lookups by keeping data sorted in blocks." },
  { id: "db-09", category: "dbms", difficulty: "advanced", sentence: "Two phase locking ensures transactions run in a serializable order." },
  { id: "db-10", category: "dbms", difficulty: "advanced", sentence: "Concurrency control prevents lost updates and dirty reads in a multiuser database." },
  { id: "db-11", category: "dbms", difficulty: "beginner", sentence: "A query selects, filters, and sorts rows from one or more tables." },
  { id: "db-12", category: "dbms", difficulty: "intermediate", sentence: "The JOIN operation combines rows from related tables on a common key." },

  // ── Operating Systems ─────────────────────────────────────────────────────
  { id: "os-01", category: "os", difficulty: "beginner", sentence: "The operating system manages processes, memory, files, and hardware resources." },
  { id: "os-02", category: "os", difficulty: "beginner", sentence: "A process is a program in execution with its own memory space." },
  { id: "os-03", category: "os", difficulty: "intermediate", sentence: "A thread is a lightweight unit of execution within a process." },
  { id: "os-04", category: "os", difficulty: "intermediate", sentence: "The scheduler decides which process runs on the CPU and for how long." },
  { id: "os-05", category: "os", difficulty: "intermediate", sentence: "Paging divides memory into fixed size frames to manage virtual memory." },
  { id: "os-06", category: "os", difficulty: "advanced", sentence: "Round robin scheduling gives every process an equal time slice in rotation." },
  { id: "os-07", category: "os", difficulty: "advanced", sentence: "Semaphores coordinate access to shared resources and prevent race conditions." },
  { id: "os-08", category: "os", difficulty: "advanced", sentence: "A deadlock occurs when processes wait forever on resources held by each other." },
  { id: "os-09", category: "os", difficulty: "advanced", sentence: "Virtual memory uses disk space as an extension of physical memory." },
  { id: "os-10", category: "os", difficulty: "advanced", sentence: "Interrupts let hardware pause the CPU so the kernel can service urgent events." },
  { id: "os-11", category: "os", difficulty: "intermediate", sentence: "A file system organizes data into files and directories on storage devices." },
  { id: "os-12", category: "os", difficulty: "beginner", sentence: "A shell is a program that lets users run commands on the operating system." },

  // ── Computer Networks ─────────────────────────────────────────────────────
  { id: "net-01", category: "networks", difficulty: "beginner", sentence: "A network connects computers so they can share data and resources." },
  { id: "net-02", category: "networks", difficulty: "beginner", sentence: "An IP address identifies a device on a network, like a postal address." },
  { id: "net-03", category: "networks", difficulty: "intermediate", sentence: "The TCP protocol guarantees reliable, ordered delivery of data packets." },
  { id: "net-04", category: "networks", difficulty: "intermediate", sentence: "HTTP is the application protocol that powers communication on the web." },
  { id: "net-05", category: "networks", difficulty: "intermediate", sentence: "Routers forward packets between networks by reading destination addresses." },
  { id: "net-06", category: "networks", difficulty: "advanced", sentence: "The OSI model layers network communication into seven distinct functions." },
  { id: "net-07", category: "networks", difficulty: "advanced", sentence: "A subnet mask separates the network portion of an IP address from the host." },
  { id: "net-08", category: "networks", difficulty: "advanced", sentence: "UDP is a connectionless protocol that trades reliability for lower latency." },
  { id: "net-09", category: "networks", difficulty: "advanced", sentence: "A domain name system translates human readable names into IP addresses." },
  { id: "net-10", category: "networks", difficulty: "intermediate", sentence: "Encryption protects data in transit so eavesdroppers cannot read it." },
  { id: "net-11", category: "networks", difficulty: "beginner", sentence: "A router connects different networks while a switch connects devices on one network." },
  { id: "net-12", category: "networks", difficulty: "advanced", sentence: "Congestion control algorithms adjust sending rates to avoid network collapse." },

  // ── AI / ML ───────────────────────────────────────────────────────────────
  { id: "ai-01", category: "aiml", difficulty: "beginner", sentence: "Machine learning trains models to find patterns from data without explicit rules." },
  { id: "ai-02", category: "aiml", difficulty: "beginner", sentence: "Supervised learning maps labeled inputs to known target outputs." },
  { id: "ai-03", category: "aiml", difficulty: "intermediate", sentence: "Linear regression models the relationship between features and a continuous target." },
  { id: "ai-04", category: "aiml", difficulty: "intermediate", sentence: "Classification models assign inputs to one of several predefined classes." },
  { id: "ai-05", category: "aiml", difficulty: "intermediate", sentence: "A neural network learns by adjusting weights through a process called backpropagation." },
  { id: "ai-06", category: "aiml", difficulty: "advanced", sentence: "Gradient descent iteratively updates weights to minimize the loss function." },
  { id: "ai-07", category: "aiml", difficulty: "advanced", sentence: "Overfitting happens when a model memorizes training noise and fails on new data." },
  { id: "ai-08", category: "aiml", difficulty: "advanced", sentence: "Reinforcement learning agents maximize cumulative reward through trial and error." },
  { id: "ai-09", category: "aiml", difficulty: "advanced", sentence: "A support vector machine finds the hyperplane that best separates the classes." },
  { id: "ai-10", category: "aiml", difficulty: "intermediate", sentence: "Feature engineering transforms raw data into inputs that improve model performance." },
  { id: "ai-11", category: "aiml", difficulty: "beginner", sentence: "An AI system perceives its environment and acts to achieve a goal." },
  { id: "ai-12", category: "aiml", difficulty: "advanced", sentence: "Deep learning stacks many layers to learn hierarchical representations of data." },

  // ── Web Development ───────────────────────────────────────────────────────
  { id: "web-01", category: "webdev", difficulty: "beginner", sentence: "HTML defines the structure and content of a web page." },
  { id: "web-02", category: "webdev", difficulty: "beginner", sentence: "CSS controls the presentation, layout, and styling of web content." },
  { id: "web-03", category: "webdev", difficulty: "intermediate", sentence: "JavaScript adds interactivity and dynamic behavior to web pages." },
  { id: "web-04", category: "webdev", difficulty: "intermediate", sentence: "The document object model lets scripts read and change page structure." },
  { id: "web-05", category: "webdev", difficulty: "intermediate", sentence: "Responsive design uses flexible layouts so pages adapt to any screen size." },
  { id: "web-06", category: "webdev", difficulty: "advanced", sentence: "React builds interfaces from reusable components and a virtual DOM." },
  { id: "web-07", category: "webdev", difficulty: "advanced", sentence: "Application programming interfaces let clients exchange data using HTTP." },
  { id: "web-08", category: "webdev", difficulty: "intermediate", sentence: "A browser cache stores resources locally to speed up repeated visits." },
  { id: "web-09", category: "webdev", difficulty: "advanced", sentence: "Server side rendering sends ready HTML so pages load faster on the first request." },
  { id: "web-10", category: "webdev", difficulty: "advanced", sentence: "Web accessibility ensures that content is usable by people of all abilities." },
  { id: "web-11", category: "webdev", difficulty: "beginner", sentence: "A hyperlink connects one web resource to another and creates navigation." },
  { id: "web-12", category: "webdev", difficulty: "advanced", sentence: "Progressive web apps combine the reach of the web with app like capabilities." },

  // ── Cybersecurity ─────────────────────────────────────────────────────────
  { id: "sec-01", category: "security", difficulty: "beginner", sentence: "Cybersecurity protects systems, networks, and data from digital attacks." },
  { id: "sec-02", category: "security", difficulty: "beginner", sentence: "A strong password is long, unique, and never reused across accounts." },
  { id: "sec-03", category: "security", difficulty: "intermediate", sentence: "Encryption scrambles data so only authorized parties can read it." },
  { id: "sec-04", category: "security", difficulty: "intermediate", sentence: "A firewall filters traffic based on a defined set of security rules." },
  { id: "sec-05", category: "security", difficulty: "intermediate", sentence: "Phishing tricks users into revealing credentials through deceptive messages." },
  { id: "sec-06", category: "security", difficulty: "advanced", sentence: "Authentication verifies identity while authorization controls what a user may do." },
  { id: "sec-07", category: "security", difficulty: "advanced", sentence: "A man in the middle attack intercepts and alters communication between parties." },
  { id: "sec-08", category: "security", difficulty: "advanced", sentence: "SQL injection abuses unsafe queries to manipulate a database." },
  { id: "sec-09", category: "security", difficulty: "advanced", sentence: "Cross site scripting injects malicious scripts into trusted web pages." },
  { id: "sec-10", category: "security", difficulty: "advanced", sentence: "Two factor authentication adds a second proof beyond the password." },
  { id: "sec-11", category: "security", difficulty: "intermediate", sentence: "A vulnerability is a weakness that an attacker could exploit." },
  { id: "sec-12", category: "security", difficulty: "advanced", sentence: "Digital signatures prove the origin and integrity of a message." },

  // ── Mathematics ───────────────────────────────────────────────────────────
  { id: "math-01", category: "math", difficulty: "beginner", sentence: "A derivative measures how fast a function changes at a point." },
  { id: "math-02", category: "math", difficulty: "beginner", sentence: "An integral computes the area under a curve over an interval." },
  { id: "math-03", category: "math", difficulty: "intermediate", sentence: "A matrix is a rectangular array of numbers arranged in rows and columns." },
  { id: "math-04", category: "math", difficulty: "intermediate", sentence: "The determinant of a matrix reveals whether its inverse exists." },
  { id: "math-05", category: "math", difficulty: "intermediate", sentence: "Linear regression finds the line that best fits a set of data points." },
  { id: "math-06", category: "math", difficulty: "advanced", sentence: "Eigenvectors are vectors that only scale when multiplied by their matrix." },
  { id: "math-07", category: "math", difficulty: "advanced", sentence: "Probability measures the likelihood that an uncertain event will occur." },
  { id: "math-08", category: "math", difficulty: "advanced", sentence: "A differential equation relates a function to its own derivatives." },
  { id: "math-09", category: "math", difficulty: "advanced", sentence: "The laplace transform converts differential equations into algebraic ones." },
  { id: "math-10", category: "math", difficulty: "intermediate", sentence: "Logarithms convert multiplication into simpler addition of exponents." },
  { id: "math-11", category: "math", difficulty: "beginner", sentence: "Prime numbers have exactly two distinct positive divisors, one and itself." },
  { id: "math-12", category: "math", difficulty: "advanced", sentence: "Vector spaces require closure under addition and scalar multiplication." },

  // ── Computer Science Fundamentals ─────────────────────────────────────────
  { id: "csf-01", category: "csfundamentals", difficulty: "beginner", sentence: "Computer science is the study of computation, information, and automated reasoning." },
  { id: "csf-02", category: "csfundamentals", difficulty: "beginner", sentence: "Abstraction hides complex details behind a simple, well defined interface." },
  { id: "csf-03", category: "csfundamentals", difficulty: "intermediate", sentence: "A bit is the smallest unit of data and can hold a value of zero or one." },
  { id: "csf-04", category: "csfundamentals", difficulty: "intermediate", sentence: "A byte groups eight bits and can represent two hundred fifty six values." },
  { id: "csf-05", category: "csfundamentals", difficulty: "intermediate", sentence: "A compiler translates an entire program before it runs." },
  { id: "csf-06", category: "csfundamentals", difficulty: "intermediate", sentence: "An interpreter translates and executes source code line by line." },
  { id: "csf-07", category: "csfundamentals", difficulty: "advanced", sentence: "Turing machines formalize what can and cannot be computed." },
  { id: "csf-08", category: "csfundamentals", difficulty: "advanced", sentence: "The halting problem proves that no program can decide whether every program stops." },
  { id: "csf-09", category: "csfundamentals", difficulty: "advanced", sentence: "P versus NP asks whether easy to verify problems are also easy to solve." },
  { id: "csf-10", category: "csfundamentals", difficulty: "advanced", sentence: "Finite state machines model systems that move between a finite set of states." },
  { id: "csf-11", category: "csfundamentals", difficulty: "intermediate", sentence: "Boolean logic uses operators like AND, OR, and NOT to combine conditions." },
  { id: "csf-12", category: "csfundamentals", difficulty: "advanced", sentence: "The cache memory hierarchy trades speed for capacity at each level." },
  { id: "csf-13", category: "csfundamentals", difficulty: "beginner", sentence: "An operating system is the software that manages a computer's hardware." },
  { id: "csf-14", category: "csfundamentals", difficulty: "advanced", sentence: "Encapsulation bundles data with the methods that operate on it." },
];

export function getSeedSentences(): TypingSentence[] {
  return curated;
}
